# Change these first
owner: vizirco # Your GitHub organization or username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  # - name: Dashboard
  #   url: https://dashboard.vizir.co
  # - name: API
  #   url: $CONTENT_SERVER
  # - name: Chatbot Web
  #   url: https://chat.vizir.co
  # - name: Website
  #   url: https://vizir.co
  # - name: Aide
  #   url: https://help.vizir.co
  # - name: API Conversation Manager
  #   url: $CHATSERVER
  # - name: API Chatbot Web
  #   url: $SOCKET_SERVER
  # - name: API Livechat
  #   url: $LIVESERVER
  # - name: Chatbot Teams
  #   url: $TEAMS_SERVER
assignees:
  - bguivarch

status-website:
  favicon: https://www.vizir.co/wp-content/uploads/2019/04/cropped-favicon-32x32.png
  faviconSvg: https://help.vizir.co/assets/favicons/favicon.ico
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.vizir.co
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://www.vizir.co/wp-content/uploads/2020/11/logo.svg
  name: Status Page
  introTitle: "**Vizir** Logiciel de création de chatbots pour équipes agiles"
  introMessage: Vizir est un logiciel qui vous permet de créer et gérer des chatbots intégrés avec vos applications métiers sans aucune compétence de code nécessaire. Vos équipes et vos clients le méritent bien !
  navbar:
    - title: Site web
      href: https://vizir.co
    - title: Dashboard
      href: https://dashboard.vizir.co
    - title: Aide
      href: https://help.vizir.co

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 * * *"